micronaut:
  application:
    name: testApi
  server:
      cors:
          enabled: true
datasources:
  default:
    driver-class-name: ${DATASOURCES_DEFAULT_DRIVER:org.mariadb.jdbc.Driver}
    db-type: mariadb
    dialect: MYSQL
    jdbc-url: ${DATASOURCES_DEFAULT_URL:`jdbc:mariadb://localhost:3306/pokemon`}
    username: ${DATASOURCES_DEFAULT_USER:pokemon-db-user}
    password: ${DATASOURCES_DEFAULT_PASSWORD:123456}
liquibase:
  datasources:
    default:
      change-log: classpath:db/liquibase-changelog.yml
netty:
  default:
    allocator:
      max-order: 3